services:
  go-app-base:
    build:
      context: ../../
      dockerfile: ./.docker/go/Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    environment:
      APP_ENV: local
      PORT: 8080
      HOME: /tmp

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: demo
      RABBITMQ_PASSWORD: demo
      RABBITMQ_VHOST: /

      RABBITMQ_EXCHANGE: weather.events
      RABBITMQ_EXCHANGE_TYPE: topic
      RABBITMQ_ROUTING_KEY: weather.snapshot.fetched
    networks:
      - weather_net
    command: ["sh", "-lc", "tail -f /dev/null"]