services:
  node-app-base:
    build:
      context: ../../
      dockerfile: ./.docker/node/Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    environment:
      NODE_ENV: development
      APP_ENV: local
      PORT: 3000
      HOME: /tmp
    networks:
      - weather_net
    command: ["sh", "-lc", "tail -f /dev/null"]
