services:
  ingestion-weatherapi:
    extends:
      file: ../../compose/common/go-app.base.yml
      service: go-app-base
    container_name: ingestion-weatherapi
    volumes:
      - ../../services/ingestion-weatherapi:/app
    environment:
      DB_HOST: ingestion-weatherapi-db
      DB_PORT: 5432
      DB_NAME: ingestion_weatherapi_db
      DB_USER: demo
      DB_PASSWORD: demo

      WEATHERAPI_BASE_URL: https://api.weatherapi.com/v1
      WEATHERAPI_KEY: ${WEATHERAPI_KEY}
    depends_on:
      - rabbitmq
      - ingestion-weatherapi-db
    ports:
      - "8081:8080"