services:
  weather-comparison:
    extends:
      file: ../../compose/common/node-app.base.yml
      service: node-app-base
    container_name: weather-comparison
    volumes:
      - ../../services/weather-comparison:/app
    environment:
      SERVICE_NAME: weather-comparison
      PROCESSING_CORE_API_BASE_URL: http://processing-core:8080
    depends_on:
      - processing-core
    ports:
      - "3001:3000"
    command: ["sh", "-lc", "npm run start:dev"]
